import {
  Alert02Icon,
  ArrowHorizontalIcon,
  ArrowVerticalIcon,
  Calendar04Icon,
  Cancel01Icon,
  CheckIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  Cursor02Icon,
  DashboardSquare01Icon,
  FileNotFoundIcon,
  FilterIcon,
  HashIcon,
  Home01Icon,
  InformationCircleIcon,
  InvoiceIcon,
  Location06Icon,
  MaterialAndTextureIcon,
  ScrollIcon,
  Sorting01Icon,
  SortingAZ02Icon,
  SortingNineOneIcon,
  SortingOneNineIcon,
  SortingZA01Icon,
  SquareIcon,
  Tag01Icon,
  Tag02Icon,
} from "@hugeicons/core-free-icons";
import type { HugeIcon } from "@/components/Icon";

// one place mapping a concept to its icon — edit here, not at each call site
export const ICONS = {
  reference: HashIcon,
  designation: Tag01Icon,
  date: Calendar04Icon,
  location: Location06Icon,
  conteneur: Tag02Icon,
  length: ArrowHorizontalIcon,
  width: ArrowVerticalIcon,
  pieces: HashIcon,
  surfacePiece: SquareIcon,
  surfaceTotale: DashboardSquare01Icon,
  surfaceDesignation: MaterialAndTextureIcon,
  bonCommande: InvoiceIcon,
  actions: Cursor02Icon,
  details: InformationCircleIcon,
  history: ScrollIcon,

  filter: FilterIcon,
  sort: Sorting01Icon,
  chevronDown: ChevronDownIcon,
  chevronLeft: ChevronLeftIcon,
  chevronRight: ChevronRightIcon,
  increasingNumber: SortingOneNineIcon,
  decreasingNumber: SortingNineOneIcon,
  increasingText: SortingAZ02Icon,
  decreasingText: SortingZA01Icon,
  cancel: Cancel01Icon,
  check: CheckIcon,
  alert: Alert02Icon,
  notFound: FileNotFoundIcon,
  home: Home01Icon,
} satisfies Record<string, HugeIcon>;
